apiVersion: v1
kind: Service

metadata:
  name: blue-green-backend
  labels:
    app: backend-blue-green

spec:
  type: LoadBalancer
  ports:
    - name: http-port
      port: 5000
      targetPort: 80
      protocol: TCP
  selector:
    app: backend-blue
    # app: backend-green