apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend-blue-deployment
  labels:
    app: backend-blue

spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-blue

  template:
    metadata:
      labels:
        app: backend-blue
    spec:
      containers:
        - name: blue-container
          image: othom/e-commerce-backend:blue-lts
          resources:
            requests:
              cpu: '10m' #1% of a core
              memory: '150Mi'
            limits:
              cpu: '50m' #5% of a core
              memory: '400Mi'
          imagePullPolicy: Always
      restartPolicy: Always
