apiVersion: v1
kind: Service

metadata:
  name: blue-green-prod-service
  labels:
    app: backend-blue-green

spec:
  type: LoadBalancer
  ports:
    - name: http-port
      port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    app: blue
    # app: green
---
apiVersion: v1
kind: Service

metadata:
  name: blue-green-straging-service
  labels:
    app: backend-blue-green

spec:
  type: LoadBalancer
  ports:
    - name: http-port
      port: 5005
      targetPort: 5005
      protocol: TCP
  selector:
    # app: blue
    app: green
