apiVersion: v1
kind: Service
metadata:
  name: bluegreen-backend
  labels:
    name: bluegreen-backend
spec:
  selector:
    app: backend-blue
  type: LoadBalancer
  ports:
    - name: http
      port: 5000
      targetPort: 5000

# apiVersion: v1
# kind: Service
# metadata:
#   name: backend-blue
#   labels:
#     app: backend-blue
#   annotations:
#     service.beta.kubernetes.io/linode-loadbalancer-throttle: '4'
# spec:
#   selector:
#     app: backend-blue
#   sessionAffinity: None
#   type: LoadBalancer
#   ports:
#     - name: http
#       port: 5000
#       protocol: TCP
#       targetPort: 5000

# apiVersion: v1
# kind: Service
# metadata:
#   name: backend-green
#   labels:
#     app: backend-green
#   annotations:
#     service.beta.kubernetes.io/linode-loadbalancer-throttle: '4'
# spec:
#   selector:
#     app: backend-green
#   sessionAffinity: None
#   type: LoadBalancer
#   ports:
#     - name: http
#       port: 5000
#       protocol: TCP
#       targetPort: 5000
