apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend-green-deployment
  labels:
    app: backend-green

spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-green

  template:
    metadata:
      labels:
        app: backend-green
    spec:
      containers:
        - name: green-container
          image: othom/e-commerce-backend:green-lts
          resources:
            requests:
              cpu: '10m' #1% of a core
              memory: '150Mi'
            limits:
              cpu: '50m' #5% of a core
              memory: '400Mi'
          imagePullPolicy: Always
      restartPolicy: Always
