apiVersion: v1
kind: Service
metadata:
  name: backend-blue
  annotations:
    service.beta.kubernetes.io/linode-loadbalancer-throttle: '4'
  labels:
    app: backend-blue
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: backend-blue
  sessionAffinity: None
