server:
  port: 5000
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  datasource:
    url: jdbc:postgresql://db-service:5432/postgres
    driver-class-name: org.h2.Driver
    username: postgres
    password: example
  h2:
    console.enabled: true

  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    host: smtp.gmail.com
    username: ${LOCALEMAIL}
    password: ${EMAILPASSWORD}
    port: '587'
