server:
  port: 5000
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop-update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
  datasource:
    platform: postgres
    url: jdbc:postgresql://db-service.p3-space.svc.cluster.local:5432/postgres?user=postgres&password=example # <service-name>.<namespace>.svc.cluster.<cluster>:<service-port>

    driver-class-name: org.postgresql.Driver
    username: postgres
    password: example

  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    host: smtp.gmail.com
    username: ${LOCALEMAIL}
    password: ${EMAILPASSWORD}
    port: '587'
