apiVersion: v1
kind: Service 
metadata:
  name: e-commerce-service
  namespace: test
  labels: 
    app: e-commerce
    tier: backend
spec:
  type: LoadBalancer
  selector: 
    app: e-commerce
    tier: backend
  ports: 
    - port: 5000 #back-end prot 
      targetPort: 5000 # this is for the container port 