apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-monitor
  namespace: monitoring
  labels:
    app: e-commerce
    prometheus: devops
    release: p3-prom-stack
spec:
  endpoints:
  - port: e-commerce-app
    path: /metrics
  namespaceSelector:
    matchNames:
    - p3-space
  selector:
    matchLabels:
      app: e-commerce
      tier: back-end
