apiVersion: v1
kind: Service 
metadata:
  name: e-commerce-service
  namespace: p3-space
  labels: 
    app: e-commerce
    tier: backend
spec: 
  selector: 
    app: e-commerce
    tier: backend
  ports: 
    - port: 5000 #back-end prot 
      targetPort: 5000 # this is for the container port 
