apiVersion: v1
kind: Service 
metadata:
  name: back-end-service
  namespace: p3-space
  labels: 
    app: back-end 
spec: 
  selector: 
    app: back-end 
  ports: 
    - port: 5000 #back-end prot 
      targetPort: 5000 # this is for the container port 
