apiVersion: v1
kind: Service 
metadata:
  name: front-end-service
  namespace: p3-space
  labels: 
    app: front-end 
spec:
  type: LoadBalancer
  selector: 
    app: front-end 
  ports: 
    - port: 80  #front-end prot  
      targetPort: 3000 # this is for the container port
        
